### ISSUE TITLE
Bug: authorization page does not open

### ISSUE THREAD

**Issue by AlexandraLesnikova** [hexlet-codebattle/codebattle#2109]
### Summary

login and password page does not open. it is not possible to log in and register

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/
2. Click the button "Sing in"
```

### Expected result

authorization page opens

### Actual result

![Image](https://github.com/user-attachments/assets/c5e4a351-4507-4063-9e8e-b933241ba5c2) a blank page opens. DevTools has a 404 error.

### Browsers

Firefox

### OS

Linux

**Comment by Aleksandr02031989** [comment]
---
- summary: |
    When authorizing via Discord, the user is not logged in.
  environment: |
    - Browser version: 133.0.6943.142 (Official build), (64 bit).
    - Operating system: Windows 10.
  steps-to-reproduce: |
    - Open the main page of the site.
    - Click the “Sign in” button.
    - On the authorization page, click “Sign in with Discord”.
  expected-result: >
    - The user is successfully authorized through Discord.
    - The user is redirected to the main page.
  actual-result: >
    - User is not authorized.
    - No content when replying. Status 204.
  attachments: |
    - Screenshot of the authorization page.

![Image](https://github.com/user-attachments/assets/14cce0e7-66b5-47cb-975d-c5a3344ef8b9)

**Comment by vtm9** [comment]
fixed

**Comment by UnprotectedL** [comment]
Went through the reproduction steps. Following error still persists after confirming authorization with Discord (redirect from Discord back to Codebattle)

Enviroment:
Opera GX v 116.0.5366.148
Windows 10 Pro 22H2 19045.5487

![Image](https://github.com/user-attachments/assets/9bbb810a-0b21-4b16-aadc-c71918d59a9b)

![Image](https://github.com/user-attachments/assets/1d092d30-8588-4794-a348-42342877557f)
